config/routes.rb
Rails.application.routes.draw do
  get 'rooms/new'

  get 'rooms/edit'

  get 'rooms/show'

  get 'rooms/create'

  get 'rooms/update'

  get 'rooms/index'

  get 'rooms/annonces'

  get '/your_trips' => 'reservations#your_trips'

  get '/your_reservations' => 'reservations#your_reservations'

  get 'pages/aidezmoi'

  get 'pages/charte'
  get 'pages/informations'
  get 'pages/conditions'
  devise_for :users,
              :path => '',
               :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
               :controllers =>{:registrations => 'registrations' }

  root 'rooms#index'

  resources :users, only: [:show]
  resources :rooms
  resources :rooms do
              resources :reservations, only: [:create]
              resources :reviews, only: [:create, :destroy]
   end

  resources :photos
  resources :conversations, only: [:index, :create] do

         resources :messages, only: [:index, :create]

 end

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

before_action :authenticate_user!

def create

      @reservation = current_user.reservations.create(reservation_params)       
      redirect_to @reservation.room, notice: "Votre ajout aux favoris a été accepté"
end

def your_trips
       @trips = current_user.reservations 
end

def your_reservations
      @rooms = current_user.rooms
end
 
private

     def reservation_params         
        params.require(:reservation).permit(:price, :room_id)     
     end 
end

app/views/reservations/_form.html.erb
<%= form_for([@room, @room.reservations.new]) do |f| %>

<!-- affichage de prix -->
<div class="row">
        <div class="col-md-12 price_tag">
            <span>€ <%= @room.price %></span>
            <span class="pull-right">Par mois</span>
        </div>
    </div>


         <div class="row">
        <div class="col-md-12" id="connection_pour_l_annonce">
        <% if (user_signed_in?) %>
            <% else %>
        <%="Veuillez-vous connecter pour afficher:" %>
        <%end%>
        </div>
         </div>
         <div class="row">
         <div class="col-md-6">
         <label><i class="fa fa-facebook-square" aria-hidden="true"></i> Facebook :</label>
         </div>
        <div class="col-md-6">
         <label><i class="fa fa-envelope-square" aria-hidden="true"></i> Email :</label>
         </div>
         </div>
         <div class="row">
         <div class="col-md-6">
            <% if (user_signed_in?) %>
                <a href="<%= @room.facebook %>" target="_blank">Lien facebook</a>
                <% else %>
            <%end%>
         </div>
        <div class="col-md-6">
            <% if (user_signed_in?) %>
            <%= @room.email %>
                <% else %>
            <%end%>
         </div>
         </div>


         <div class="row">
         <div class="col-md-6">
            <label><i class="fa fa-phone-square" aria-hidden="true"></i> Téléphone :</label>
         </div>
        <div class="col-md-6">
         </div>
         </div>

        <div class="row">
         <div class="col-md-6">
            <% if (user_signed_in?) %>
                <%= @room.numero %>
                <% else %>
            <%end%>
         </div>

         </div>


     <%= f.hidden_field :room_id, value: @room.id %> <!-- champs caché pour renseigner l’id du logement et le prix -->
     <%= f.hidden_field :price, value: @room.price %>
 <br>
     <%= f.submit "Ajouter à mes favoris", class: "btn btn-primary wide" %>

 <% end %>

app/views/reservations/your_reservations.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Mes annonces", rooms_annonces_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes annonces mises en favoris", your_reservations_path, class:"sidebar-link active" %></li>
            <li class="sidebar-item"><%= link_to "Mes favoris", your_trips_path, class:"sidebar-link" %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">Mes annonces mises en favoris</div>
            <div class="panel-body">
                <% @rooms.each do |room| %>
                <% room.reservations.order("id DESC").each do |reservation| %>
                <div class="row">
                   <div class="col-md-2">
                   </div>
                   <div class="col-md-6">
                       <%= link_to room_path(reservation.room) do %>
                           <%= image_tag reservation.room.photos[0].image.url(:thumb) if reservation.room.photos.length > 0 %>
                       <% end %>
                   </div>
                   <div class="col-md-2">
                       <%= link_to user_path(reservation.user) do %>
                           <%= image_tag avatar_url(reservation.user), class:"img-circle avatar-medium" %>
                       <% end %>
                   </div>
                   <div class="col-md-2 right">
                       <h4><%= reservation.price %> €</h4>
                   </div>
                </div>
                <hr>
                <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Mes annonces", rooms_annonces_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes annonces mises en favoris", your_reservations_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes favoris", your_trips_path, class:"sidebar-link active" %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading"> Mes favoris</div>
            <div class="panel-body">
                <% @trips.order("id DESC").each do |trip| %>
                <div class="row">
                   <div class="col-md-2">
                   </div>
                   <div class="col-md-6">
                       <%= link_to room_path(trip.room) do %>
                           <%= image_tag trip.room.photos[0].image.url(:thumb) if trip.room.photos.length > 0 %>
                       <% end %>
                   </div>
                   <div class="col-md-2">
                       <%= link_to user_path(trip.room.user) do %>
                           <%= image_tag avatar_url(trip.room.user), class:"img-circle avatar-medium" %>
                       <% end %>
                   </div>
                   <div class="col-md-2 right">
                       <h4><%= trip.price %> €</h4>
                   </div>
                </div>
                <hr>
                <% end %>
            </div>
        </div>
    </div>
</div>