config/routes.rb
Rails.application.routes.draw do
  get 'rooms/new'

  get 'rooms/edit'

  get 'rooms/show'

  get 'rooms/create'

  get 'rooms/update'

  get 'rooms/index'

  get 'rooms/annonces'

  get '/your_trips' => 'reservations#your_trips'

  get '/your_reservations' => 'reservations#your_reservations'

  get 'pages/aidezmoi'

  get 'pages/charte'
  get 'pages/informations'
  get 'pages/conditions'
  devise_for :users,
              :path => '',
               :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
               :controllers =>{:registrations => 'registrations' }

  root 'rooms#index'

  resources :users, only: [:show]
  resources :rooms
  resources :rooms do
              resources :reservations, only: [:create]
              resources :reviews, only: [:create, :destroy]
   end

  resources :photos
  resources :conversations, only: [:index, :create] do

         resources :messages, only: [:index, :create]

 end

end

app/views/layouts/_footer.html.erb
<style type="text/css">
  #container_footer{
    display: flex;
    justify-content: center;
  }
  #footer_item{
    flex: 1;
  }
</style>
<footer class="footer">
    <div class="container">
        <div class="row">
          <div class="col-md-offset-2 col-md-10">
              <span class="navbar-text" id="footer_item">
                <%= link_to 'Aidez-moi :)',  pages_aidezmoi_path %>
              </span>
              <span class="navbar-text" id="footer_item">
                <%= link_to 'Charte',  pages_charte_path %>
              </span>

              <span class="navbar-text" id="footer_item">
                <%= link_to 'Informations légales',  pages_informations_path %>
              </span>

              <span class="navbar-text" id="footer_item">
                <%= link_to 'Politique de confidentialité',  pages_conditions_path %>
              </span>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">
    <%=link_to(image_tag("logokedgeimmonav.png"),root_path)%>
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse right">
      <ul class="nav navbar-nav navbar-right">

        <li>
          <%= link_to new_room_path do %>
          <i class="fa fa-home fa-lg"></i>
          Propose un logement
          <% end %>
        </li>

        <% if (!user_signed_in?) %>
        <!-- lien vers l'inscription s'il n'est pas inscrit ni connecté -->

        <li><%= link_to 'Inscription', new_user_registration_path %></li>
        <li><%= link_to 'Connexion', new_user_session_path %></li>

      <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="identifiant">
            <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>
            <%= current_user.fullname %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Mes annonces", rooms_annonces_path %></li>
            <li><%= link_to "Mes favoris", your_reservations_path %></li>
            <li><%= link_to conversations_path do %>Messages<% end %></li>
            <li><%= link_to 'Modifier le profil', edit_user_registration_path %></li>
            <li><%= link_to 'Déconnexion', destroy_user_session_path,method: :delete %></li>
          </ul>
        </li>
        <% end %>

      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kedge Immo</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link href="https://fonts.googleapis.com/css?family=Fredoka+One|Hammersmith+One|Open+Sans:800i|Paytone+One" rel="stylesheet">    <meta name="viewport" content="width=device-width">
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>

    <%= render 'layouts/navigation' %>
    <!-- alert : déconnexion et connexion avec succès -->
    <%= render 'shared/message' %>

    <div class="container"><%= yield %></div>
    <br><br><br>
    <%= render 'layouts/footer' %>
  </body>

</html>